{"name": "test_sub[minus]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3\n  +2\n  -3", "trace": "self = <test_calc.TestCalc object at 0x10618ed90>, a = 0, b = -2, expect = 2, myfixture = None\n\n    @pytest.mark.run(order=3)   # 用例排序\n    @pytest.mark.flaky(retuns=3, reruns_delay=2)    # 失败后重新运行\n    @pytest.mark.parametrize('a,b,expect', get_datas()[1], ids=get_datas()[4])  # 数据驱动\n    def test_sub(self, a, b, expect, myfixture):\n>       assert expect == a - b + 1\nE       assert 2 == 3\nE         +2\nE         -3\n\ntest_calc.py:35: AssertionError"}, "parameters": [{"name": "a", "value": "0"}, {"name": "b", "value": "-2"}, {"name": "expect", "value": "2"}], "start": 1608121002342, "stop": 1608121002343, "uuid": "59074279-7b02-4408-96db-796eff279d4f", "historyId": "e8250a00e43a261aa44d48df177e89c2", "testCaseId": "3b960671b7ce69bb509e37e84b3024bc", "fullName": "test_calc.TestCalc#test_sub", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "flaky(retuns=3, reruns_delay=2)"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "bogon"}, {"name": "thread", "value": "92175-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}